name = "hanabicode-website"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
main = "./src/server-entry.ts"

workers_dev = true

[observability]
enabled = true

[[kv_namespaces]]
binding = "WEBSITE_CACHE"
id = "REPLACE_WITH_FORK_KV_NAMESPACE_ID"
